### ISSUE TITLE
Bug Ticket: Module Import Error Due to Incorrect File Path

### ISSUE THREAD

**Issue by AliceKitchkin** [gflachs/GreenPrompt_LLM_Registry#19]
**Description**
There is currently a workaround in place for importing the function start_model_instance in the test_process_start.py file within the GreenPrompt_LLM_Registry project. The existing implementation modifies the system path dynamically, which is not ideal for long-term maintainability. The root cause of the issue is that attempting to import start_model_instance using a relative path (from src.app.llm_registry import start_model_instance) results in a ModuleNotFoundError.

**Error**
Traceback (most recent call last): from src.app.llm_registry import start_model_instance ModuleNotFoundError: No module named 'src'.

**Temporary Solution**
`BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))`
`sys.path.insert(0, os.path.join(BASE_DIR, 'src'))`
`from app.llm_registry import start_model_instance`

**Comment by gflachs** [comment]
Use the `python -m package.module` to run them
