### ISSUE TITLE
Development of a Central Service for Managing Model Instances

### ISSUE THREAD

**Issue by ruppfabian1997** [gflachs/GreenPrompt_LLM_Registry#3]
## Userstory

As a developer, I want the central service to start a new service for a specific model configuration, so that each model runs in an isolated and manageable environment.

## Acceptance Criteria:

  Scenario: Accepting a model configuration as input
    Given the central service is prepared to accept model configurations
    When a model configuration is provided as input
    Then the service should accept the model configuration

  Scenario: Simulating starting an LLM
    Given the model configuration has been accepted
    When the service simulates starting an LLM
    Then the service should simulate the startup process

  Scenario: Logging errors during service startup
    Given an error occurs during the service startup
    When the error is encountered
    Then the error should be logged

  Scenario: Returning an appropriate error message
    Given the service startup encounters an error
    When the error occurs
    Then an appropriate error message should be returned

## Test Criteria:

- Verify that the central service starts a new process or container for the given model configuration.
- Validate that the started service is running and accepting requests.

**Comment by AliceKitchkin** [comment]
**Working hours (will be updated continuously)**
1. Sprint (18.11. - 29.11.): 2h
2. Sprint (02.12. - 13.12.): 1h
